[tool.poetry]
name = 'RodgersICA'
version = '0.1.0'

[tool.poetry.dependencies]
python = '^3.6'
numpy = '^1.22'

[build-system]
requires = ['poetry-core~=1.0']
build-backend = 'poetry.core.masonry.api'